
project_id = "aoieaspnfqddcdsizqgv"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600

[db]
port = 54322

[functions.update-trending-tools]
verify_jwt = false

[functions.paystack-ipn]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[edge-runtime]
enabled = true
policy = "oneshot"
inspector_port = 8083

[storage]
enabled = true
file_size_limit = "50MiB"

[functions.billing-webhook]
verify_jwt = false

[functions.subscription-status]
verify_jwt = true

[functions.billing-reconciliation]
verify_jwt = false

[functions.billing-cron]
verify_jwt = false

[functions.paystack-initialize]
verify_jwt = true

[functions.paystack-verify]
verify_jwt = false

[functions.paystack-cancel-subscription]
verify_jwt = true

[functions.refresh-subscription]
verify_jwt = true

[functions.send-password-reset]  
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.me]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false
