
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aoieaspnfqddcdsizqgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvaWVhc3BuZnFkZGNkc2l6cWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjU1MzksImV4cCI6MjA2NTUwMTUzOX0.JMSvYjdR-JrsR-BlQpbeHAUXtOs_jR0YJRgURq0z-xw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: false,
    detectSessionInUrl: false,
    flowType: 'pkce',
    debug: false,
    storageKey: 'aitouse-auth-token',
  }
});
